on: [ 'push', 'pull_request' ]

name: Build PHPUnit

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  phpunit:
    name: Build PHPUnit for Swoole
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        php-version: [ '7.3', '7.4' ]
      max-parallel: 2
      fail-fast: false
    env:
      PHPUNIT_VERSION: '9.5.4'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download PHPUnit
        run: |
          wget https://github.com/sebastianbergmann/phpunit/archive/refs/tags/${PHPUNIT_VERSION}.tar.gz -O build.tar.gz
          mkdir -p build
          tar -xf build.tar.gz -C build --strip-components=1
          rm build.tar.gz
      - name: Setup Components
        run: composer update -o --no-dev
