on: [ 'push', 'pull_request' ]

name: Build PHPUnit

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  phpunit:
    name: Build PHPUnit for Swoole
    runs-on: ubuntu-latest
    needs: release
    env:
      PHPUNIT_VERSION: '9.5.4'
      SW_VERSION: '4.6.4'
      PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter, redis, pdo, pdo_mysql
      PHP_INI_VALUES: assert.exception=1, phar.readonly=0, zend.assertions=1, xdebug.remote_autostart=0, xdebug.remote_enable=0
    strategy:
      matrix:
        php-version: [ '7.3', '7.4' ]
      max-parallel: 2
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download PHPUnit
        run: |
          git clone --branch ${PHPUNIT_VERSION} --depth 1 https://github.com/sebastianbergmann/phpunit.git build
      - name: Setup Swoole
        run: |
          sudo apt-get install libcurl4-openssl-dev
          wget https://github.com/swoole/swoole-src/archive/v${SW_VERSION}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-http2 --enable-swoole-curl --enable-swoole-json
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          sudo sh -c "echo swoole.use_shortname='Off' >> /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          php --ri swoole
          ls /etc/php/${{ matrix.php-version }}/cli/conf.d/
      - name: Generate PHPUnit Stub
        run: |
          composer update -o
          php bin/hyperf.php gen:phpunit
      - name: Build PHAR
        run: |
          cd build
          ant phar-nightly
          cp ./build/artifacts/phpunit-nightly.phar ../phpunit.phar
      - name: Run Test
        run: ./phpunit.phar
